In [1]:
import pandas as pd
import optuna
import numpy as np
import lightgbm as lgb
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
import shap
import wandb
from Optune_simulation_env import get_best_params, walk_forward_predict_test
from utils import load_data
from scipy.stats import ttest_rel
from statsmodels.tsa.statespace.sarimax import SARIMAX

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
N_TRIALS = 30
FINAL_TEST_DAYS = 30
OPTUNA_VAL_DAYS = 30
N_Optuna_Runs = 17
COUNTRY = "HU"

In [3]:
real_ds = load_data("real", COUNTRY)

In [4]:
display(real_ds)
print(real_ds.columns)

,last_y,lag_1_t0,lag_4_t0,lag_8_t0,lag_24_t0,lag_96_t0,lag_192_t0,lag_672_t0,ramp_1h_t0,ramp_6h_t0,...,daily_weight_lag_1w,hour_weight_lag_1d,hour_weight_lag_2d,hour_weight_lag_1w,daily_avg_weight_lag_1d,daily_avg_weight_lag_2d,daily_avg_weight_lag_1w,hour_avg_weight_lag_1d,hour_avg_weight_lag_2d,hour_avg_weight_lag_1w
ts,,,,,,,,,,,,,,,,,,,,,
2025-10-23 00:00:00+02:00,105.92,114.01,112.68,107.79,273.76,105.62,131.97,116.57,-6.76,-167.84,...,0.009603,0.274744,0.274857,0.265149,0.767645,0.866840,0.921894,1.098978,1.099429,1.060595
2025-10-23 00:15:00+02:00,105.92,114.01,112.68,107.79,273.76,100.00,122.11,117.07,-6.76,-167.84,...,0.009644,0.260125,0.254322,0.266286,0.726799,0.802075,0.925849,1.040502,1.017287,1.065144
2025-10-23 00:30:00+02:00,105.92,114.01,112.68,107.79,273.76,89.81,120.99,106.52,-6.76,-167.84,...,0.008775,0.233619,0.251989,0.242289,0.652738,0.794718,0.842414,0.934474,1.007956,0.969157
2025-10-23 00:45:00+02:00,105.92,114.01,112.68,107.79,273.76,89.00,105.07,99.48,-6.76,-167.84,...,0.008195,0.231512,0.218832,0.226276,0.646851,0.690148,0.786738,0.926046,0.875328,0.905104
2025-10-23 01:00:00+02:00,105.92,114.01,112.68,107.79,273.76,100.75,101.19,108.09,-6.76,-167.84,...,0.008904,0.263213,0.270576,0.260671,0.732250,0.664663,0.854830,1.052852,1.082304,1.042686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-13 22:45:00+01:00,110.99,126.34,120.48,128.76,299.49,120.48,131.51,121.74,-9.49,-188.50,...,0.011154,0.204759,0.236895,0.232942,0.894156,1.184665,1.070824,0.819035,0.947581,0.931767
2026-03-13 23:00:00+01:00,110.99,126.34,120.48,128.76,299.49,149.77,138.85,140.81,-9.49,-188.50,...,0.012902,0.297216,0.295696,0.270113,1.111535,1.250785,1.238564,1.188863,1.182784,1.080453
2026-03-13 23:15:00+01:00,110.99,126.34,120.48,128.76,299.49,116.81,114.68,131.12,-9.49,-188.50,...,0.012014,0.231807,0.244223,0.251525,0.866919,1.033057,1.153331,0.927229,0.976894,1.006100
2026-03-13 23:30:00+01:00,110.99,126.34,120.48,128.76,299.49,126.34,111.55,128.65,-9.49,-188.50,...,0.011788,0.250719,0.237558,0.246787,0.937647,1.004862,1.131605,1.002877,0.950231,0.987148
2026-03-13 23:45:00+01:00,110.99,126.34,120.48,128.76,299.49,110.99,104.49,120.72,-9.49,-188.50,...,0.011061,0.220258,0.222523,0.231575,0.823725,0.941264,1.061852,0.881030,0.890091,0.926300

Index(['last_y', 'lag_1_t0', 'lag_4_t0', 'lag_8_t0', 'lag_24_t0', 'lag_96_t0',
       'lag_192_t0', 'lag_672_t0', 'ramp_1h_t0', 'ramp_6h_t0', 'ramp_1d_t0',
       'roll_mean_24_t0', 'roll_std_24_t0', 'roll_mean_96_t0',
       'roll_std_96_t0', 'roll_mean_672_t0', 'roll_std_672_t0', 'h',
       'q_in_hour_target', 'qod_target', 'hod_target', 'dow_target',
       'month_target', 'is_weekend_target', 'q_in_hour_sin', 'q_in_hour_cos',
       'qod_sin', 'qod_cos', 'hod_sin', 'hod_cos', 'dow_sin', 'dow_cos',
       'month_sin', 'month_cos', 'load_fc_target', 'renewables_wind_fc',
       'renewables_solar_fc', 'load_ramp_1h_target', 'load_ramp_6h_target',
       'load_ramp_12h_target', 'load_day_mean', 'load_day_max', 'load_day_min',
       'y_target', 'is_synthetic', 'is_observed', 'day', 'daily_weight_lag_1d',
       'daily_weight_lag_2d', 'daily_weight_lag_1w', 'hour_weight_lag_1d',
       'hour_weight_lag_2d', 'hour_weight_lag_1w', 'daily_avg_weight_lag_1d',
       'daily_avg_weight_lag_2d', 'daily_avg_weight_lag_1w',
       'hour_avg_weight_lag_1d', 'hour_avg_weight_lag_2d',
       'hour_avg_weight_lag_1w'],
      dtype='object')

In [5]:
test_df = real_ds[["y_target", "lag_96_t0", "day"]]
print(test_df)

                           y_target  lag_96_t0                        day
ts
2025-10-23 00:00:00+02:00    117.43     105.62  2025-10-23 00:00:00+02:00
2025-10-23 00:15:00+02:00    111.14     100.00  2025-10-23 00:00:00+02:00
2025-10-23 00:30:00+02:00    103.57      89.81  2025-10-23 00:00:00+02:00
2025-10-23 00:45:00+02:00    100.16      89.00  2025-10-23 00:00:00+02:00
2025-10-23 01:00:00+02:00    114.63     100.75  2025-10-23 00:00:00+02:00
...                             ...        ...                        ...
2026-03-13 22:45:00+01:00    116.90     120.48  2026-03-13 00:00:00+01:00
2026-03-13 23:00:00+01:00    133.69     149.77  2026-03-13 00:00:00+01:00
2026-03-13 23:15:00+01:00    115.61     116.81  2026-03-13 00:00:00+01:00
2026-03-13 23:30:00+01:00    115.10     126.34  2026-03-13 00:00:00+01:00
2026-03-13 23:45:00+01:00    103.35     110.99  2026-03-13 00:00:00+01:00

[13632 rows x 3 columns]

In [6]:
all_days = np.array(sorted(test_df["day"].unique()))
final_test_days = all_days[-FINAL_TEST_DAYS:]
tune_days = all_days[:-FINAL_TEST_DAYS]

print(final_test_days)

['2026-02-12 00:00:00+01:00' '2026-02-13 00:00:00+01:00'
 '2026-02-14 00:00:00+01:00' '2026-02-15 00:00:00+01:00'
 '2026-02-16 00:00:00+01:00' '2026-02-17 00:00:00+01:00'
 '2026-02-18 00:00:00+01:00' '2026-02-19 00:00:00+01:00'
 '2026-02-20 00:00:00+01:00' '2026-02-21 00:00:00+01:00'
 '2026-02-22 00:00:00+01:00' '2026-02-23 00:00:00+01:00'
 '2026-02-24 00:00:00+01:00' '2026-02-25 00:00:00+01:00'
 '2026-02-26 00:00:00+01:00' '2026-02-27 00:00:00+01:00'
 '2026-02-28 00:00:00+01:00' '2026-03-01 00:00:00+01:00'
 '2026-03-02 00:00:00+01:00' '2026-03-03 00:00:00+01:00'
 '2026-03-04 00:00:00+01:00' '2026-03-05 00:00:00+01:00'
 '2026-03-06 00:00:00+01:00' '2026-03-07 00:00:00+01:00'
 '2026-03-08 00:00:00+01:00' '2026-03-09 00:00:00+01:00'
 '2026-03-10 00:00:00+01:00' '2026-03-11 00:00:00+01:00'
 '2026-03-12 00:00:00+01:00' '2026-03-13 00:00:00+01:00']

In [7]:
ds_test_pool  = test_df[test_df["day"].isin(final_test_days)].copy()
display(ds_test_pool)

                           y_target  lag_96_t0                        day
ts
2026-02-12 00:00:00+01:00     96.36     102.95  2026-02-12 00:00:00+01:00
2026-02-12 00:15:00+01:00     94.85     104.25  2026-02-12 00:00:00+01:00
2026-02-12 00:30:00+01:00     96.79     102.89  2026-02-12 00:00:00+01:00
2026-02-12 00:45:00+01:00     94.61     102.55  2026-02-12 00:00:00+01:00
2026-02-12 01:00:00+01:00     96.36     102.88  2026-02-12 00:00:00+01:00
...                             ...        ...                        ...
2026-03-13 22:45:00+01:00    116.90     120.48  2026-03-13 00:00:00+01:00
2026-03-13 23:00:00+01:00    133.69     149.77  2026-03-13 00:00:00+01:00
2026-03-13 23:15:00+01:00    115.61     116.81  2026-03-13 00:00:00+01:00
2026-03-13 23:30:00+01:00    115.10     126.34  2026-03-13 00:00:00+01:00
2026-03-13 23:45:00+01:00    103.35     110.99  2026-03-13 00:00:00+01:00

[2880 rows x 3 columns]

In [8]:
print(real_ds)

                           last_y  lag_1_t0  lag_4_t0  lag_8_t0  lag_24_t0  \
ts
2025-10-23 00:00:00+02:00  105.92    114.01    112.68    107.79     273.76
2025-10-23 00:15:00+02:00  105.92    114.01    112.68    107.79     273.76
2025-10-23 00:30:00+02:00  105.92    114.01    112.68    107.79     273.76
2025-10-23 00:45:00+02:00  105.92    114.01    112.68    107.79     273.76
2025-10-23 01:00:00+02:00  105.92    114.01    112.68    107.79     273.76
...                           ...       ...       ...       ...        ...
2026-03-13 22:45:00+01:00  110.99    126.34    120.48    128.76     299.49
2026-03-13 23:00:00+01:00  110.99    126.34    120.48    128.76     299.49
2026-03-13 23:15:00+01:00  110.99    126.34    120.48    128.76     299.49
2026-03-13 23:30:00+01:00  110.99    126.34    120.48    128.76     299.49
2026-03-13 23:45:00+01:00  110.99    126.34    120.48    128.76     299.49

                           lag_96_t0  lag_192_t0  lag_672_t0  ramp_1h_t0  \
ts
2025-10-23 00:00:00+02:00     105.62      131.97      116.57       -6.76
2025-10-23 00:15:00+02:00     100.00      122.11      117.07       -6.76
2025-10-23 00:30:00+02:00      89.81      120.99      106.52       -6.76
2025-10-23 00:45:00+02:00      89.00      105.07       99.48       -6.76
2025-10-23 01:00:00+02:00     100.75      101.19      108.09       -6.76
...                              ...         ...         ...         ...
2026-03-13 22:45:00+01:00     120.48      131.51      121.74       -9.49
2026-03-13 23:00:00+01:00     149.77      138.85      140.81       -9.49
2026-03-13 23:15:00+01:00     116.81      114.68      131.12       -9.49
2026-03-13 23:30:00+01:00     126.34      111.55      128.65       -9.49
2026-03-13 23:45:00+01:00     110.99      104.49      120.72       -9.49

                           ramp_6h_t0  ...  daily_weight_lag_1w  \
ts                                     ...
2025-10-23 00:00:00+02:00     -167.84  ...             0.009603
2025-10-23 00:15:00+02:00     -167.84  ...             0.009644
2025-10-23 00:30:00+02:00     -167.84  ...             0.008775
2025-10-23 00:45:00+02:00     -167.84  ...             0.008195
2025-10-23 01:00:00+02:00     -167.84  ...             0.008904
...                               ...  ...                  ...
2026-03-13 22:45:00+01:00     -188.50  ...             0.011154
2026-03-13 23:00:00+01:00     -188.50  ...             0.012902
2026-03-13 23:15:00+01:00     -188.50  ...             0.012014
2026-03-13 23:30:00+01:00     -188.50  ...             0.011788
2026-03-13 23:45:00+01:00     -188.50  ...             0.011061

                           hour_weight_lag_1d  hour_weight_lag_2d  \
ts
2025-10-23 00:00:00+02:00            0.274744            0.274857
2025-10-23 00:15:00+02:00            0.260125            0.254322
2025-10-23 00:30:00+02:00            0.233619            0.251989
2025-10-23 00:45:00+02:00            0.231512            0.218832
2025-10-23 01:00:00+02:00            0.263213            0.270576
...                                       ...                 ...
2026-03-13 22:45:00+01:00            0.204759            0.236895
2026-03-13 23:00:00+01:00            0.297216            0.295696
2026-03-13 23:15:00+01:00            0.231807            0.244223
2026-03-13 23:30:00+01:00            0.250719            0.237558
2026-03-13 23:45:00+01:00            0.220258            0.222523

                           hour_weight_lag_1w  daily_avg_weight_lag_1d  \
ts
2025-10-23 00:00:00+02:00            0.265149                 0.767645
2025-10-23 00:15:00+02:00            0.266286                 0.726799
2025-10-23 00:30:00+02:00            0.242289                 0.652738
2025-10-23 00:45:00+02:00            0.226276                 0.646851
2025-10-23 01:00:00+02:00            0.260671                 0.732250
...                                       ...                      ...
2026-03-13 22:45:00+01:00            0.232942                 0.894156
2026-03-13 23:00:00+01:00            0.270113                 1.111535
2026-03-13 23:15:00+01:00            0.251525                 0.866919
2026-03-13 23:30:00+01:00            0.246787                 0.937647
2026-03-13 23:45:00+01:00            0.231575                 0.823725

                           daily_avg_weight_lag_2d  daily_avg_weight_lag_1w  \
ts
2025-10-23 00:00:00+02:00                 0.866840                 0.921894
2025-10-23 00:15:00+02:00                 0.802075                 0.925849
2025-10-23 00:30:00+02:00                 0.794718                 0.842414
2025-10-23 00:45:00+02:00                 0.690148                 0.786738
2025-10-23 01:00:00+02:00                 0.664663                 0.854830
...                                            ...                      ...
2026-03-13 22:45:00+01:00                 1.184665                 1.070824
2026-03-13 23:00:00+01:00                 1.250785                 1.238564
2026-03-13 23:15:00+01:00                 1.033057                 1.153331
2026-03-13 23:30:00+01:00                 1.004862                 1.131605
2026-03-13 23:45:00+01:00                 0.941264                 1.061852

                           hour_avg_weight_lag_1d  hour_avg_weight_lag_2d  \
ts
2025-10-23 00:00:00+02:00                1.098978                1.099429
2025-10-23 00:15:00+02:00                1.040502                1.017287
2025-10-23 00:30:00+02:00                0.934474                1.007956
2025-10-23 00:45:00+02:00                0.926046                0.875328
2025-10-23 01:00:00+02:00                1.052852                1.082304
...                                           ...                     ...
2026-03-13 22:45:00+01:00                0.819035                0.947581
2026-03-13 23:00:00+01:00                1.188863                1.182784
2026-03-13 23:15:00+01:00                0.927229                0.976894
2026-03-13 23:30:00+01:00                1.002877                0.950231
2026-03-13 23:45:00+01:00                0.881030                0.890091

                           hour_avg_weight_lag_1w
ts
2025-10-23 00:00:00+02:00                1.060595
2025-10-23 00:15:00+02:00                1.065144
2025-10-23 00:30:00+02:00                0.969157
2025-10-23 00:45:00+02:00                0.905104
2025-10-23 01:00:00+02:00                1.042686
...                                           ...
2026-03-13 22:45:00+01:00                0.931767
2026-03-13 23:00:00+01:00                1.080453
2026-03-13 23:15:00+01:00                1.006100
2026-03-13 23:30:00+01:00                0.987148
2026-03-13 23:45:00+01:00                0.926300

[13632 rows x 59 columns]

In [9]:
# Rolling SARIMAX forecast: use the previous day(s) to predict the next day at 15-minute resolution.
# Seasonal order uses a daily seasonality of 96 periods (24h * 4 samples per hour).
sarimax_order = (1, 1, 1)
sarimax_seasonal_order = (1, 1, 1, 96)

def sarimax_rolling_forecast(df, test_days, target_col="y_target", order=sarimax_order, seasonal_order=sarimax_seasonal_order, window_days=1):
    df = df.sort_values(["day"]).copy()
    df["day"] = pd.to_datetime(df["day"])
    df["step_in_day"] = df.groupby("day").cumcount()

    forecasts = []
    for day in test_days:
        day = pd.to_datetime(day)
        window_start = day - pd.Timedelta(days=window_days)
        train_data = df[(df["day"] >= window_start) & (df["day"] < day)][target_col].astype(float)
        print(train_data)
        if len(train_data) < 96:
            raise ValueError(f"Not enough history before {day.date()} to fit SARIMAX. Need at least 96 rows.")

        model = SARIMAX(
            train_data,
            order=order,
            seasonal_order=seasonal_order,
            enforce_stationarity=False,
            enforce_invertibility=False,
        )
        fitted = model.fit(disp=False)
        pred = fitted.get_forecast(steps=96).predicted_mean

        forecasts.append(pd.DataFrame({
            "day": [day] * len(pred),
            "step_in_day": np.arange(len(pred)),
            "y_pred": pred,
        }))

    return pd.concat(forecasts, ignore_index=True)

sarimax_preds = sarimax_rolling_forecast(
    real_ds,
    final_test_days,
    order=sarimax_order,
    seasonal_order=sarimax_seasonal_order,
    window_days=7,
)

ds_test_pool = ds_test_pool.copy()
ds_test_pool["day"] = pd.to_datetime(ds_test_pool["day"])
ds_test_pool["step_in_day"] = ds_test_pool.groupby("day").cumcount()
ds_test_pool = ds_test_pool.merge(sarimax_preds, on=["day", "step_in_day"], how="left")
display(ds_test_pool.head(10))

ts
2026-02-05 15:00:00+01:00    130.99
2026-02-05 17:15:00+01:00    147.60
2026-02-05 17:00:00+01:00    140.10
2026-02-05 16:45:00+01:00    159.71
2026-02-05 16:30:00+01:00    149.34
                              ...
2026-02-11 07:30:00+01:00    144.37
2026-02-11 07:45:00+01:00    148.02
2026-02-11 08:00:00+01:00    143.22
2026-02-11 08:15:00+01:00    148.42
2026-02-11 07:15:00+01:00    138.67
Name: y_target, Length: 672, dtype: float64

C:\Users\local_user\AppData\Local\Temp\ipykernel_8968\1056855811.py:8: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df["day"] = pd.to_datetime(df["day"])
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-06 15:30:00+01:00    160.11
2026-02-06 17:30:00+01:00    182.13
2026-02-06 17:15:00+01:00    178.91
2026-02-06 17:00:00+01:00    188.16
2026-02-06 16:45:00+01:00    170.97
                              ...
2026-02-12 07:30:00+01:00    137.34
2026-02-12 07:45:00+01:00    140.39
2026-02-12 08:00:00+01:00    135.10
2026-02-12 08:15:00+01:00    137.32
2026-02-12 07:15:00+01:00    135.63
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-07 17:30:00+01:00    142.05
2026-02-07 17:15:00+01:00    136.04
2026-02-07 17:00:00+01:00    132.91
2026-02-07 16:45:00+01:00    137.86
2026-02-07 16:30:00+01:00    130.55
                              ...
2026-02-13 07:15:00+01:00    122.63
2026-02-13 07:00:00+01:00    114.99
2026-02-13 06:45:00+01:00    123.21
2026-02-13 06:30:00+01:00    114.23
2026-02-13 08:45:00+01:00    123.48
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-08 17:45:00+01:00    136.84
2026-02-08 15:45:00+01:00    114.94
2026-02-08 16:00:00+01:00    105.86
2026-02-08 16:15:00+01:00    113.20
2026-02-08 17:30:00+01:00    134.37
                              ...
2026-02-14 07:00:00+01:00     97.50
2026-02-14 06:45:00+01:00    100.36
2026-02-14 06:30:00+01:00     96.63
2026-02-14 06:15:00+01:00     96.85
2026-02-14 08:15:00+01:00    113.76
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-09 17:45:00+01:00    239.28
2026-02-09 15:45:00+01:00    178.81
2026-02-09 16:00:00+01:00    149.41
2026-02-09 16:15:00+01:00    167.50
2026-02-09 17:30:00+01:00    227.79
                              ...
2026-02-15 07:30:00+01:00    107.72
2026-02-15 07:15:00+01:00    108.27
2026-02-15 07:00:00+01:00    109.17
2026-02-15 08:45:00+01:00    105.93
2026-02-15 06:30:00+01:00    108.21
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-10 17:15:00+01:00    164.18
2026-02-10 17:00:00+01:00    154.29
2026-02-10 16:45:00+01:00    176.99
2026-02-10 16:30:00+01:00    161.74
2026-02-10 16:15:00+01:00    159.04
                              ...
2026-02-16 06:30:00+01:00    142.82
2026-02-16 07:45:00+01:00    139.96
2026-02-16 08:00:00+01:00    135.94
2026-02-16 08:15:00+01:00    135.82
2026-02-16 07:30:00+01:00    144.11
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-11 15:45:00+01:00    139.11
2026-02-11 16:00:00+01:00    128.34
2026-02-11 16:15:00+01:00    136.34
2026-02-11 17:30:00+01:00    147.14
2026-02-11 16:45:00+01:00    150.52
                              ...
2026-02-17 12:00:00+01:00    102.55
2026-02-17 08:00:00+01:00    139.42
2026-02-17 08:15:00+01:00    137.14
2026-02-17 00:00:00+01:00     94.69
2026-02-17 07:45:00+01:00    140.83
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-12 17:15:00+01:00    151.01
2026-02-12 17:00:00+01:00    140.28
2026-02-12 16:45:00+01:00    154.82
2026-02-12 16:30:00+01:00    144.93
2026-02-12 16:15:00+01:00    135.09
                              ...
2026-02-18 06:15:00+01:00    116.97
2026-02-18 07:30:00+01:00    191.50
2026-02-18 07:45:00+01:00    204.08
2026-02-18 08:00:00+01:00    207.78
2026-02-18 08:15:00+01:00    198.51
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-13 17:15:00+01:00    161.86
2026-02-13 17:00:00+01:00    128.24
2026-02-13 16:45:00+01:00    154.21
2026-02-13 16:30:00+01:00    133.05
2026-02-13 16:15:00+01:00    128.67
                              ...
2026-02-19 07:15:00+01:00    147.16
2026-02-19 07:00:00+01:00    141.38
2026-02-19 06:45:00+01:00    139.14
2026-02-19 06:30:00+01:00    126.61
2026-02-19 08:45:00+01:00    136.34
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-14 15:30:00+01:00    114.24
2026-02-14 15:45:00+01:00    122.72
2026-02-14 16:00:00+01:00    118.17
2026-02-14 17:15:00+01:00    144.40
2026-02-14 16:30:00+01:00    140.10
                              ...
2026-02-20 07:30:00+01:00    147.98
2026-02-20 07:45:00+01:00    145.70
2026-02-20 08:00:00+01:00    139.52
2026-02-20 08:15:00+01:00    135.95
2026-02-20 07:15:00+01:00    155.24
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-15 16:00:00+01:00     84.00
2026-02-15 16:15:00+01:00    101.79
2026-02-15 16:30:00+01:00    107.50
2026-02-15 17:45:00+01:00    135.17
2026-02-15 17:00:00+01:00    113.82
                              ...
2026-02-21 06:15:00+01:00     81.18
2026-02-21 07:30:00+01:00     90.00
2026-02-21 07:45:00+01:00     92.96
2026-02-21 08:00:00+01:00     98.67
2026-02-21 07:15:00+01:00     89.06
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-16 16:00:00+01:00    119.60
2026-02-16 16:15:00+01:00    136.25
2026-02-16 16:30:00+01:00    213.42
2026-02-16 16:45:00+01:00    174.34
2026-02-16 17:45:00+01:00    159.99
                              ...
2026-02-22 06:15:00+01:00     62.90
2026-02-22 07:45:00+01:00     83.38
2026-02-22 08:00:00+01:00     45.46
2026-02-22 07:30:00+01:00     72.71
2026-02-22 11:15:00+01:00     70.25
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-17 15:45:00+01:00    142.62
2026-02-17 17:45:00+01:00    174.36
2026-02-17 17:30:00+01:00    174.29
2026-02-17 17:15:00+01:00    167.34
2026-02-17 17:00:00+01:00    152.87
                              ...
2026-02-23 06:00:00+01:00     58.08
2026-02-23 07:30:00+01:00    115.21
2026-02-23 07:45:00+01:00    111.00
2026-02-23 08:00:00+01:00    119.39
2026-02-23 07:15:00+01:00    118.12
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-18 15:15:00+01:00    117.54
2026-02-18 17:15:00+01:00    167.68
2026-02-18 17:00:00+01:00    139.61
2026-02-18 16:45:00+01:00    153.38
2026-02-18 16:30:00+01:00    151.06
                              ...
2026-02-24 07:30:00+01:00    132.73
2026-02-24 07:45:00+01:00    139.84
2026-02-24 08:00:00+01:00    136.54
2026-02-24 08:15:00+01:00    136.73
2026-02-24 07:15:00+01:00    123.71
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-19 17:15:00+01:00    176.72
2026-02-19 17:00:00+01:00    154.06
2026-02-19 16:45:00+01:00    161.09
2026-02-19 16:30:00+01:00    157.84
2026-02-19 16:15:00+01:00    152.54
                              ...
2026-02-25 07:15:00+01:00    137.17
2026-02-25 07:00:00+01:00    126.14
2026-02-25 06:45:00+01:00    142.96
2026-02-25 06:30:00+01:00    130.37
2026-02-25 08:45:00+01:00    114.27
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-20 15:45:00+01:00    112.59
2026-02-20 16:00:00+01:00    104.00
2026-02-20 16:15:00+01:00    121.00
2026-02-20 17:30:00+01:00    169.22
2026-02-20 16:45:00+01:00    136.13
                              ...
2026-02-26 07:15:00+01:00    119.68
2026-02-26 07:00:00+01:00    118.83
2026-02-26 06:45:00+01:00    132.22
2026-02-26 08:30:00+01:00    107.30
2026-02-26 06:15:00+01:00    111.24
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-21 17:15:00+01:00    106.17
2026-02-21 17:00:00+01:00    101.90
2026-02-21 16:45:00+01:00    107.39
2026-02-21 16:30:00+01:00    102.01
2026-02-21 16:15:00+01:00     93.10
                              ...
2026-02-27 07:30:00+01:00    120.55
2026-02-27 07:45:00+01:00     99.85
2026-02-27 08:00:00+01:00    103.08
2026-02-27 08:15:00+01:00     95.23
2026-02-27 07:15:00+01:00    130.70
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-22 17:15:00+01:00     97.58
2026-02-22 17:00:00+01:00     93.69
2026-02-22 16:45:00+01:00    104.75
2026-02-22 16:30:00+01:00     90.23
2026-02-22 16:15:00+01:00     86.00
                              ...
2026-02-28 07:00:00+01:00     89.26
2026-02-28 06:45:00+01:00     82.38
2026-02-28 06:30:00+01:00     81.11
2026-02-28 06:15:00+01:00     78.86
2026-02-28 08:30:00+01:00     55.72
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-23 15:00:00+01:00     59.69
2026-02-23 17:15:00+01:00    143.10
2026-02-23 17:00:00+01:00    170.00
2026-02-23 16:45:00+01:00    169.99
2026-02-23 16:30:00+01:00    150.00
                              ...
2026-03-01 07:00:00+01:00     74.12
2026-03-01 06:45:00+01:00     72.86
2026-03-01 06:30:00+01:00     73.05
2026-03-01 06:15:00+01:00     70.66
2026-03-01 08:45:00+01:00     46.91
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-24 15:30:00+01:00    113.57
2026-02-24 17:30:00+01:00    184.89
2026-02-24 17:15:00+01:00    149.51
2026-02-24 17:00:00+01:00    129.13
2026-02-24 16:45:00+01:00    146.26
                              ...
2026-03-02 07:30:00+01:00    147.99
2026-03-02 07:45:00+01:00    126.70
2026-03-02 08:00:00+01:00    187.23
2026-03-02 08:15:00+01:00    127.64
2026-03-02 07:15:00+01:00    172.51
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-25 17:30:00+01:00    157.22
2026-02-25 17:15:00+01:00    144.44
2026-02-25 17:00:00+01:00    121.71
2026-02-25 16:45:00+01:00    142.21
2026-02-25 16:30:00+01:00    110.12
                              ...
2026-03-03 07:15:00+01:00    164.24
2026-03-03 07:00:00+01:00    170.23
2026-03-03 06:45:00+01:00    183.28
2026-03-03 06:30:00+01:00    134.89
2026-03-03 08:45:00+01:00     91.68
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-26 17:45:00+01:00    128.87
2026-02-26 15:45:00+01:00     99.80
2026-02-26 16:00:00+01:00     69.76
2026-02-26 16:15:00+01:00     97.11
2026-02-26 17:30:00+01:00    122.68
                              ...
2026-03-04 07:00:00+01:00    313.45
2026-03-04 06:45:00+01:00    317.65
2026-03-04 06:30:00+01:00    223.72
2026-03-04 08:15:00+01:00    130.62
2026-03-04 06:00:00+01:00    144.39
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-27 15:45:00+01:00    100.73
2026-02-27 16:00:00+01:00     81.99
2026-02-27 16:15:00+01:00     94.44
2026-02-27 16:30:00+01:00    109.29
2026-02-27 17:30:00+01:00    144.52
                              ...
2026-03-05 07:30:00+01:00    160.00
2026-03-05 07:45:00+01:00    146.50
2026-03-05 08:00:00+01:00    176.43
2026-03-05 08:15:00+01:00    149.94
2026-03-05 07:15:00+01:00    190.62
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-02-28 17:15:00+01:00     95.67
2026-02-28 17:00:00+01:00     90.77
2026-02-28 16:45:00+01:00    100.08
2026-02-28 16:30:00+01:00     95.87
2026-02-28 16:15:00+01:00     64.10
                              ...
2026-03-06 07:15:00+01:00    190.84
2026-03-06 07:00:00+01:00    210.62
2026-03-06 06:45:00+01:00    184.88
2026-03-06 06:30:00+01:00    167.17
2026-03-06 08:45:00+01:00     74.59
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-01 17:45:00+01:00    126.42
2026-03-01 15:45:00+01:00     76.44
2026-03-01 16:00:00+01:00     43.24
2026-03-01 16:15:00+01:00     67.88
2026-03-01 17:30:00+01:00    124.15
                              ...
2026-03-07 07:00:00+01:00    154.22
2026-03-07 06:45:00+01:00    140.81
2026-03-07 06:30:00+01:00    149.69
2026-03-07 06:15:00+01:00    146.96
2026-03-07 08:30:00+01:00     77.70
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-02 15:30:00+01:00     92.55
2026-03-02 15:45:00+01:00    116.53
2026-03-02 16:00:00+01:00     86.95
2026-03-02 16:15:00+01:00    112.85
2026-03-02 17:30:00+01:00    197.62
                              ...
2026-03-08 07:30:00+01:00    112.06
2026-03-08 07:45:00+01:00     91.76
2026-03-08 08:00:00+01:00    121.81
2026-03-08 08:15:00+01:00     61.12
2026-03-08 07:15:00+01:00    131.04
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-03 17:15:00+01:00    181.56
2026-03-03 17:00:00+01:00    151.39
2026-03-03 16:45:00+01:00    167.49
2026-03-03 16:30:00+01:00    120.63
2026-03-03 16:15:00+01:00    100.61
                              ...
2026-03-09 07:15:00+01:00    207.51
2026-03-09 07:00:00+01:00    208.71
2026-03-09 06:45:00+01:00    186.16
2026-03-09 06:30:00+01:00    184.63
2026-03-09 08:45:00+01:00     62.09
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-04 15:30:00+01:00    107.27
2026-03-04 15:45:00+01:00    137.00
2026-03-04 16:00:00+01:00     96.37
2026-03-04 17:15:00+01:00    179.20
2026-03-04 16:30:00+01:00    142.69
                              ...
2026-03-10 07:30:00+01:00    194.73
2026-03-10 07:45:00+01:00    175.21
2026-03-10 08:00:00+01:00    150.00
2026-03-10 08:15:00+01:00    149.99
2026-03-10 07:15:00+01:00    217.74
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-05 15:45:00+01:00    122.37
2026-03-05 16:00:00+01:00     93.04
2026-03-05 16:15:00+01:00    123.60
2026-03-05 16:30:00+01:00    148.84
2026-03-05 17:30:00+01:00    195.38
                              ...
2026-03-11 06:15:00+01:00    174.39
2026-03-11 07:45:00+01:00     73.99
2026-03-11 08:00:00+01:00     96.62
2026-03-11 08:15:00+01:00     88.51
2026-03-11 07:30:00+01:00     84.41
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it is not monotonic and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

ts
2026-03-06 17:30:00+01:00    174.68
2026-03-06 17:15:00+01:00    142.42
2026-03-06 17:00:00+01:00    106.33
2026-03-06 16:45:00+01:00    176.14
2026-03-06 16:30:00+01:00    141.96
                              ...
2026-03-12 06:15:00+01:00    180.04
2026-03-12 07:45:00+01:00    121.14
2026-03-12 08:00:00+01:00    145.22
2026-03-12 08:15:00+01:00    109.60
2026-03-12 07:30:00+01:00    156.72
Name: y_target, Length: 672, dtype: float64

c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
c:\Users\local_user\anaconda3\envs\EnergyPrices\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

   y_target  lag_96_t0                       day  step_in_day      y_pred
0     96.36     102.95 2026-02-12 00:00:00+01:00            0  173.103788
1     94.85     104.25 2026-02-12 00:00:00+01:00            1  158.195934
2     96.79     102.89 2026-02-12 00:00:00+01:00            2  153.650813
3     94.61     102.55 2026-02-12 00:00:00+01:00            3  158.973509
4     96.36     102.88 2026-02-12 00:00:00+01:00            4  169.185087
5     95.53     102.80 2026-02-12 00:00:00+01:00            5  163.882016
6     94.67     102.76 2026-02-12 00:00:00+01:00            6  159.182600
7     96.67     102.46 2026-02-12 00:00:00+01:00            7  161.368393
8     96.50     101.78 2026-02-12 00:00:00+01:00            8  144.256987
9     96.00     102.28 2026-02-12 00:00:00+01:00            9  143.679140

In [10]:
mae = mean_absolute_error(ds_test_pool["y_target"], ds_test_pool["lag_96_t0"])
rmse = root_mean_squared_error(y_true=ds_test_pool["y_target"], y_pred=ds_test_pool["lag_96_t0"])

print("Baseline lag_96_t0:", mae, rmse)

mae_sarimax = mean_absolute_error(ds_test_pool["y_target"], ds_test_pool["y_pred"])
rmse_sarimax = root_mean_squared_error(y_true=ds_test_pool["y_target"], y_pred=ds_test_pool["y_pred"])
print("SARIMAX rolling:", mae_sarimax, rmse_sarimax)

Baseline lag_96_t0: 21.602489583333334 31.164018339464825
SARIMAX rolling: 54.19361218619484 73.55351164302772